//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace RBDL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EINS_RBMS_EMAILEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EINS_RBMS_EMAILEntities object using the connection string found in the 'EINS_RBMS_EMAILEntities' section of the application configuration file.
        /// </summary>
        public EINS_RBMS_EMAILEntities() : base("name=EINS_RBMS_EMAILEntities", "EINS_RBMS_EMAILEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EINS_RBMS_EMAILEntities object.
        /// </summary>
        public EINS_RBMS_EMAILEntities(string connectionString) : base(connectionString, "EINS_RBMS_EMAILEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EINS_RBMS_EMAILEntities object.
        /// </summary>
        public EINS_RBMS_EMAILEntities(EntityConnection connection) : base(connection, "EINS_RBMS_EMAILEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Column> Columns
        {
            get
            {
                if ((_Columns == null))
                {
                    _Columns = base.CreateObjectSet<Column>("Columns");
                }
                return _Columns;
            }
        }
        private ObjectSet<Column> _Columns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmailConfiguration> EmailConfigurations
        {
            get
            {
                if ((_EmailConfigurations == null))
                {
                    _EmailConfigurations = base.CreateObjectSet<EmailConfiguration>("EmailConfigurations");
                }
                return _EmailConfigurations;
            }
        }
        private ObjectSet<EmailConfiguration> _EmailConfigurations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Form> Forms
        {
            get
            {
                if ((_Forms == null))
                {
                    _Forms = base.CreateObjectSet<Form>("Forms");
                }
                return _Forms;
            }
        }
        private ObjectSet<Form> _Forms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TableStructure> TableStructures
        {
            get
            {
                if ((_TableStructures == null))
                {
                    _TableStructures = base.CreateObjectSet<TableStructure>("TableStructures");
                }
                return _TableStructures;
            }
        }
        private ObjectSet<TableStructure> _TableStructures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EventManager> EventManagers
        {
            get
            {
                if ((_EventManagers == null))
                {
                    _EventManagers = base.CreateObjectSet<EventManager>("EventManagers");
                }
                return _EventManagers;
            }
        }
        private ObjectSet<EventManager> _EventManagers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Columns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToColumns(Column column)
        {
            base.AddObject("Columns", column);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmailConfigurations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmailConfigurations(EmailConfiguration emailConfiguration)
        {
            base.AddObject("EmailConfigurations", emailConfiguration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Forms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForms(Form form)
        {
            base.AddObject("Forms", form);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TableStructures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTableStructures(TableStructure tableStructure)
        {
            base.AddObject("TableStructures", tableStructure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EventManagers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventManagers(EventManager eventManager)
        {
            base.AddObject("EventManagers", eventManager);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="Column")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Column : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Column object.
        /// </summary>
        /// <param name="columnID">Initial value of the ColumnID property.</param>
        public static Column CreateColumn(global::System.Int32 columnID)
        {
            Column column = new Column();
            column.ColumnID = columnID;
            return column;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColumnID
        {
            get
            {
                return _ColumnID;
            }
            set
            {
                if (_ColumnID != value)
                {
                    OnColumnIDChanging(value);
                    ReportPropertyChanging("ColumnID");
                    _ColumnID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ColumnID");
                    OnColumnIDChanged();
                }
            }
        }
        private global::System.Int32 _ColumnID;
        partial void OnColumnIDChanging(global::System.Int32 value);
        partial void OnColumnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColumnName
        {
            get
            {
                return _ColumnName;
            }
            set
            {
                OnColumnNameChanging(value);
                ReportPropertyChanging("ColumnName");
                _ColumnName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ColumnName");
                OnColumnNameChanged();
            }
        }
        private global::System.String _ColumnName;
        partial void OnColumnNameChanging(global::System.String value);
        partial void OnColumnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DbColumnName
        {
            get
            {
                return _DbColumnName;
            }
            set
            {
                OnDbColumnNameChanging(value);
                ReportPropertyChanging("DbColumnName");
                _DbColumnName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DbColumnName");
                OnDbColumnNameChanged();
            }
        }
        private global::System.String _DbColumnName;
        partial void OnDbColumnNameChanging(global::System.String value);
        partial void OnDbColumnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DbtableName
        {
            get
            {
                return _DbtableName;
            }
            set
            {
                OnDbtableNameChanging(value);
                ReportPropertyChanging("DbtableName");
                _DbtableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DbtableName");
                OnDbtableNameChanged();
            }
        }
        private global::System.String _DbtableName;
        partial void OnDbtableNameChanging(global::System.String value);
        partial void OnDbtableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FormID
        {
            get
            {
                return _FormID;
            }
            set
            {
                OnFormIDChanging(value);
                ReportPropertyChanging("FormID");
                _FormID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormID");
                OnFormIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FormID;
        partial void OnFormIDChanging(Nullable<global::System.Int32> value);
        partial void OnFormIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Boolean> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Boolean> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _status;
        partial void OnstatusChanging(Nullable<global::System.Boolean> value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="EmailConfiguration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmailConfiguration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmailConfiguration object.
        /// </summary>
        /// <param name="eC_Id">Initial value of the eC_Id property.</param>
        public static EmailConfiguration CreateEmailConfiguration(global::System.Int32 eC_Id)
        {
            EmailConfiguration emailConfiguration = new EmailConfiguration();
            emailConfiguration.eC_Id = eC_Id;
            return emailConfiguration;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eC_Id
        {
            get
            {
                return _eC_Id;
            }
            set
            {
                if (_eC_Id != value)
                {
                    OneC_IdChanging(value);
                    ReportPropertyChanging("eC_Id");
                    _eC_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("eC_Id");
                    OneC_IdChanged();
                }
            }
        }
        private global::System.Int32 _eC_Id;
        partial void OneC_IdChanging(global::System.Int32 value);
        partial void OneC_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eC_SMTPServerName
        {
            get
            {
                return _eC_SMTPServerName;
            }
            set
            {
                OneC_SMTPServerNameChanging(value);
                ReportPropertyChanging("eC_SMTPServerName");
                _eC_SMTPServerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eC_SMTPServerName");
                OneC_SMTPServerNameChanged();
            }
        }
        private global::System.String _eC_SMTPServerName;
        partial void OneC_SMTPServerNameChanging(global::System.String value);
        partial void OneC_SMTPServerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eC_UserName
        {
            get
            {
                return _eC_UserName;
            }
            set
            {
                OneC_UserNameChanging(value);
                ReportPropertyChanging("eC_UserName");
                _eC_UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eC_UserName");
                OneC_UserNameChanged();
            }
        }
        private global::System.String _eC_UserName;
        partial void OneC_UserNameChanging(global::System.String value);
        partial void OneC_UserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eC_Password
        {
            get
            {
                return _eC_Password;
            }
            set
            {
                OneC_PasswordChanging(value);
                ReportPropertyChanging("eC_Password");
                _eC_Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eC_Password");
                OneC_PasswordChanged();
            }
        }
        private global::System.String _eC_Password;
        partial void OneC_PasswordChanging(global::System.String value);
        partial void OneC_PasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eC_SMTPPort
        {
            get
            {
                return _eC_SMTPPort;
            }
            set
            {
                OneC_SMTPPortChanging(value);
                ReportPropertyChanging("eC_SMTPPort");
                _eC_SMTPPort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eC_SMTPPort");
                OneC_SMTPPortChanged();
            }
        }
        private Nullable<global::System.Int32> _eC_SMTPPort;
        partial void OneC_SMTPPortChanging(Nullable<global::System.Int32> value);
        partial void OneC_SMTPPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> eC_IsSSLEnabled
        {
            get
            {
                return _eC_IsSSLEnabled;
            }
            set
            {
                OneC_IsSSLEnabledChanging(value);
                ReportPropertyChanging("eC_IsSSLEnabled");
                _eC_IsSSLEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eC_IsSSLEnabled");
                OneC_IsSSLEnabledChanged();
            }
        }
        private Nullable<global::System.Boolean> _eC_IsSSLEnabled;
        partial void OneC_IsSSLEnabledChanging(Nullable<global::System.Boolean> value);
        partial void OneC_IsSSLEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyId
        {
            get
            {
                return _CompanyId;
            }
            set
            {
                OnCompanyIdChanging(value);
                ReportPropertyChanging("CompanyId");
                _CompanyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyId");
                OnCompanyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyId;
        partial void OnCompanyIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                OnLocationIdChanging(value);
                ReportPropertyChanging("LocationId");
                _LocationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationId");
                OnLocationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationId;
        partial void OnLocationIdChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> eC_status
        {
            get
            {
                return _eC_status;
            }
            set
            {
                OneC_statusChanging(value);
                ReportPropertyChanging("eC_status");
                _eC_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eC_status");
                OneC_statusChanged();
            }
        }
        private Nullable<global::System.Boolean> _eC_status;
        partial void OneC_statusChanging(Nullable<global::System.Boolean> value);
        partial void OneC_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> eC_IsDefault
        {
            get
            {
                return _eC_IsDefault;
            }
            set
            {
                OneC_IsDefaultChanging(value);
                ReportPropertyChanging("eC_IsDefault");
                _eC_IsDefault = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eC_IsDefault");
                OneC_IsDefaultChanged();
            }
        }
        private Nullable<global::System.Boolean> _eC_IsDefault;
        partial void OneC_IsDefaultChanging(Nullable<global::System.Boolean> value);
        partial void OneC_IsDefaultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> eC_IsActive
        {
            get
            {
                return _eC_IsActive;
            }
            set
            {
                OneC_IsActiveChanging(value);
                ReportPropertyChanging("eC_IsActive");
                _eC_IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eC_IsActive");
                OneC_IsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _eC_IsActive;
        partial void OneC_IsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OneC_IsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eC_signature
        {
            get
            {
                return _eC_signature;
            }
            set
            {
                OneC_signatureChanging(value);
                ReportPropertyChanging("eC_signature");
                _eC_signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eC_signature");
                OneC_signatureChanged();
            }
        }
        private global::System.String _eC_signature;
        partial void OneC_signatureChanging(global::System.String value);
        partial void OneC_signatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eC_Pop3Server
        {
            get
            {
                return _eC_Pop3Server;
            }
            set
            {
                OneC_Pop3ServerChanging(value);
                ReportPropertyChanging("eC_Pop3Server");
                _eC_Pop3Server = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eC_Pop3Server");
                OneC_Pop3ServerChanged();
            }
        }
        private global::System.String _eC_Pop3Server;
        partial void OneC_Pop3ServerChanging(global::System.String value);
        partial void OneC_Pop3ServerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ec_Pop3Portno
        {
            get
            {
                return _ec_Pop3Portno;
            }
            set
            {
                Onec_Pop3PortnoChanging(value);
                ReportPropertyChanging("ec_Pop3Portno");
                _ec_Pop3Portno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ec_Pop3Portno");
                Onec_Pop3PortnoChanged();
            }
        }
        private Nullable<global::System.Int32> _ec_Pop3Portno;
        partial void Onec_Pop3PortnoChanging(Nullable<global::System.Int32> value);
        partial void Onec_Pop3PortnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int64> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int64> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _LastModifiedBy;
        partial void OnLastModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOn
        {
            get
            {
                return _LastModifiedOn;
            }
            set
            {
                OnLastModifiedOnChanging(value);
                ReportPropertyChanging("LastModifiedOn");
                _LastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOn");
                OnLastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOn;
        partial void OnLastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="eventsID">Initial value of the EventsID property.</param>
        public static Event CreateEvent(global::System.Int32 eventsID)
        {
            Event @event = new Event();
            @event.EventsID = eventsID;
            return @event;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventsID
        {
            get
            {
                return _EventsID;
            }
            set
            {
                if (_EventsID != value)
                {
                    OnEventsIDChanging(value);
                    ReportPropertyChanging("EventsID");
                    _EventsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventsID");
                    OnEventsIDChanged();
                }
            }
        }
        private global::System.Int32 _EventsID;
        partial void OnEventsIDChanging(global::System.Int32 value);
        partial void OnEventsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventsName
        {
            get
            {
                return _EventsName;
            }
            set
            {
                OnEventsNameChanging(value);
                ReportPropertyChanging("EventsName");
                _EventsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventsName");
                OnEventsNameChanged();
            }
        }
        private global::System.String _EventsName;
        partial void OnEventsNameChanging(global::System.String value);
        partial void OnEventsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormID
        {
            get
            {
                return _FormID;
            }
            set
            {
                OnFormIDChanging(value);
                ReportPropertyChanging("FormID");
                _FormID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormID");
                OnFormIDChanged();
            }
        }
        private global::System.String _FormID;
        partial void OnFormIDChanging(global::System.String value);
        partial void OnFormIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _status;
        partial void OnstatusChanging(Nullable<global::System.Boolean> value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="EventManager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventManager : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventManager object.
        /// </summary>
        /// <param name="eM_Id">Initial value of the eM_Id property.</param>
        public static EventManager CreateEventManager(global::System.Int32 eM_Id)
        {
            EventManager eventManager = new EventManager();
            eventManager.eM_Id = eM_Id;
            return eventManager;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eM_Id
        {
            get
            {
                return _eM_Id;
            }
            set
            {
                if (_eM_Id != value)
                {
                    OneM_IdChanging(value);
                    ReportPropertyChanging("eM_Id");
                    _eM_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("eM_Id");
                    OneM_IdChanged();
                }
            }
        }
        private global::System.Int32 _eM_Id;
        partial void OneM_IdChanging(global::System.Int32 value);
        partial void OneM_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_ModuleId
        {
            get
            {
                return _eM_ModuleId;
            }
            set
            {
                OneM_ModuleIdChanging(value);
                ReportPropertyChanging("eM_ModuleId");
                _eM_ModuleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_ModuleId");
                OneM_ModuleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_ModuleId;
        partial void OneM_ModuleIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_ModuleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_FormId
        {
            get
            {
                return _eM_FormId;
            }
            set
            {
                OneM_FormIdChanging(value);
                ReportPropertyChanging("eM_FormId");
                _eM_FormId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_FormId");
                OneM_FormIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_FormId;
        partial void OneM_FormIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_FormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_Events_Id
        {
            get
            {
                return _eM_Events_Id;
            }
            set
            {
                OneM_Events_IdChanging(value);
                ReportPropertyChanging("eM_Events_Id");
                _eM_Events_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_Events_Id");
                OneM_Events_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_Events_Id;
        partial void OneM_Events_IdChanging(Nullable<global::System.Int32> value);
        partial void OneM_Events_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_CompanyId
        {
            get
            {
                return _eM_CompanyId;
            }
            set
            {
                OneM_CompanyIdChanging(value);
                ReportPropertyChanging("eM_CompanyId");
                _eM_CompanyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_CompanyId");
                OneM_CompanyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_CompanyId;
        partial void OneM_CompanyIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_CompanyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_LocationId
        {
            get
            {
                return _eM_LocationId;
            }
            set
            {
                OneM_LocationIdChanging(value);
                ReportPropertyChanging("eM_LocationId");
                _eM_LocationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_LocationId");
                OneM_LocationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_LocationId;
        partial void OneM_LocationIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_LocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_ConfigId
        {
            get
            {
                return _eM_ConfigId;
            }
            set
            {
                OneM_ConfigIdChanging(value);
                ReportPropertyChanging("eM_ConfigId");
                _eM_ConfigId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_ConfigId");
                OneM_ConfigIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_ConfigId;
        partial void OneM_ConfigIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_ConfigIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_RuleName
        {
            get
            {
                return _eM_RuleName;
            }
            set
            {
                OneM_RuleNameChanging(value);
                ReportPropertyChanging("eM_RuleName");
                _eM_RuleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_RuleName");
                OneM_RuleNameChanged();
            }
        }
        private global::System.String _eM_RuleName;
        partial void OneM_RuleNameChanging(global::System.String value);
        partial void OneM_RuleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_Subject
        {
            get
            {
                return _eM_Subject;
            }
            set
            {
                OneM_SubjectChanging(value);
                ReportPropertyChanging("eM_Subject");
                _eM_Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_Subject");
                OneM_SubjectChanged();
            }
        }
        private global::System.String _eM_Subject;
        partial void OneM_SubjectChanging(global::System.String value);
        partial void OneM_SubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_CommonEmailBody
        {
            get
            {
                return _eM_CommonEmailBody;
            }
            set
            {
                OneM_CommonEmailBodyChanging(value);
                ReportPropertyChanging("eM_CommonEmailBody");
                _eM_CommonEmailBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_CommonEmailBody");
                OneM_CommonEmailBodyChanged();
            }
        }
        private global::System.String _eM_CommonEmailBody;
        partial void OneM_CommonEmailBodyChanging(global::System.String value);
        partial void OneM_CommonEmailBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_HostEmailBody
        {
            get
            {
                return _eM_HostEmailBody;
            }
            set
            {
                OneM_HostEmailBodyChanging(value);
                ReportPropertyChanging("eM_HostEmailBody");
                _eM_HostEmailBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_HostEmailBody");
                OneM_HostEmailBodyChanged();
            }
        }
        private global::System.String _eM_HostEmailBody;
        partial void OneM_HostEmailBodyChanging(global::System.String value);
        partial void OneM_HostEmailBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_VisitorEmailBody
        {
            get
            {
                return _eM_VisitorEmailBody;
            }
            set
            {
                OneM_VisitorEmailBodyChanging(value);
                ReportPropertyChanging("eM_VisitorEmailBody");
                _eM_VisitorEmailBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_VisitorEmailBody");
                OneM_VisitorEmailBodyChanged();
            }
        }
        private global::System.String _eM_VisitorEmailBody;
        partial void OneM_VisitorEmailBodyChanging(global::System.String value);
        partial void OneM_VisitorEmailBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_Priority
        {
            get
            {
                return _eM_Priority;
            }
            set
            {
                OneM_PriorityChanging(value);
                ReportPropertyChanging("eM_Priority");
                _eM_Priority = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_Priority");
                OneM_PriorityChanged();
            }
        }
        private global::System.String _eM_Priority;
        partial void OneM_PriorityChanging(global::System.String value);
        partial void OneM_PriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eM_Reciepients
        {
            get
            {
                return _eM_Reciepients;
            }
            set
            {
                OneM_ReciepientsChanging(value);
                ReportPropertyChanging("eM_Reciepients");
                _eM_Reciepients = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eM_Reciepients");
                OneM_ReciepientsChanged();
            }
        }
        private global::System.String _eM_Reciepients;
        partial void OneM_ReciepientsChanging(global::System.String value);
        partial void OneM_ReciepientsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int32> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int32> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _LastModifiedBy;
        partial void OnLastModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOn
        {
            get
            {
                return _LastModifiedOn;
            }
            set
            {
                OnLastModifiedOnChanging(value);
                ReportPropertyChanging("LastModifiedOn");
                _LastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOn");
                OnLastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOn;
        partial void OnLastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_Department
        {
            get
            {
                return _eM_Department;
            }
            set
            {
                OneM_DepartmentChanging(value);
                ReportPropertyChanging("eM_Department");
                _eM_Department = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_Department");
                OneM_DepartmentChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_Department;
        partial void OneM_DepartmentChanging(Nullable<global::System.Int32> value);
        partial void OneM_DepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_TemplateId
        {
            get
            {
                return _eM_TemplateId;
            }
            set
            {
                OneM_TemplateIdChanging(value);
                ReportPropertyChanging("eM_TemplateId");
                _eM_TemplateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_TemplateId");
                OneM_TemplateIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_TemplateId;
        partial void OneM_TemplateIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_TemplateIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="Form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Form : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Form object.
        /// </summary>
        /// <param name="formID">Initial value of the FormID property.</param>
        public static Form CreateForm(global::System.Int32 formID)
        {
            Form form = new Form();
            form.FormID = formID;
            return form;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormID
        {
            get
            {
                return _FormID;
            }
            set
            {
                if (_FormID != value)
                {
                    OnFormIDChanging(value);
                    ReportPropertyChanging("FormID");
                    _FormID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FormID");
                    OnFormIDChanged();
                }
            }
        }
        private global::System.Int32 _FormID;
        partial void OnFormIDChanging(global::System.Int32 value);
        partial void OnFormIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormName
        {
            get
            {
                return _FormName;
            }
            set
            {
                OnFormNameChanging(value);
                ReportPropertyChanging("FormName");
                _FormName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormName");
                OnFormNameChanged();
            }
        }
        private global::System.String _FormName;
        partial void OnFormNameChanging(global::System.String value);
        partial void OnFormNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModuleID;
        partial void OnModuleIDChanging(Nullable<global::System.Int32> value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MessageBox1
        {
            get
            {
                return _MessageBox1;
            }
            set
            {
                OnMessageBox1Changing(value);
                ReportPropertyChanging("MessageBox1");
                _MessageBox1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageBox1");
                OnMessageBox1Changed();
            }
        }
        private Nullable<global::System.Boolean> _MessageBox1;
        partial void OnMessageBox1Changing(Nullable<global::System.Boolean> value);
        partial void OnMessageBox1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MessageBox2
        {
            get
            {
                return _MessageBox2;
            }
            set
            {
                OnMessageBox2Changing(value);
                ReportPropertyChanging("MessageBox2");
                _MessageBox2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageBox2");
                OnMessageBox2Changed();
            }
        }
        private Nullable<global::System.Boolean> _MessageBox2;
        partial void OnMessageBox2Changing(Nullable<global::System.Boolean> value);
        partial void OnMessageBox2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MessageBox3
        {
            get
            {
                return _MessageBox3;
            }
            set
            {
                OnMessageBox3Changing(value);
                ReportPropertyChanging("MessageBox3");
                _MessageBox3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageBox3");
                OnMessageBox3Changed();
            }
        }
        private Nullable<global::System.Boolean> _MessageBox3;
        partial void OnMessageBox3Changing(Nullable<global::System.Boolean> value);
        partial void OnMessageBox3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageBox1_Contacts
        {
            get
            {
                return _MessageBox1_Contacts;
            }
            set
            {
                OnMessageBox1_ContactsChanging(value);
                ReportPropertyChanging("MessageBox1_Contacts");
                _MessageBox1_Contacts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageBox1_Contacts");
                OnMessageBox1_ContactsChanged();
            }
        }
        private global::System.String _MessageBox1_Contacts;
        partial void OnMessageBox1_ContactsChanging(global::System.String value);
        partial void OnMessageBox1_ContactsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageBox2_Contacts
        {
            get
            {
                return _MessageBox2_Contacts;
            }
            set
            {
                OnMessageBox2_ContactsChanging(value);
                ReportPropertyChanging("MessageBox2_Contacts");
                _MessageBox2_Contacts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageBox2_Contacts");
                OnMessageBox2_ContactsChanged();
            }
        }
        private global::System.String _MessageBox2_Contacts;
        partial void OnMessageBox2_ContactsChanging(global::System.String value);
        partial void OnMessageBox2_ContactsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageBox3_Contacts
        {
            get
            {
                return _MessageBox3_Contacts;
            }
            set
            {
                OnMessageBox3_ContactsChanging(value);
                ReportPropertyChanging("MessageBox3_Contacts");
                _MessageBox3_Contacts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageBox3_Contacts");
                OnMessageBox3_ContactsChanged();
            }
        }
        private global::System.String _MessageBox3_Contacts;
        partial void OnMessageBox3_ContactsChanging(global::System.String value);
        partial void OnMessageBox3_ContactsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _status;
        partial void OnstatusChanging(Nullable<global::System.Boolean> value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Module object.
        /// </summary>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        public static Module CreateModule(global::System.Int32 moduleID)
        {
            Module module = new Module();
            module.ModuleID = moduleID;
            return module;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                if (_ModuleID != value)
                {
                    OnModuleIDChanging(value);
                    ReportPropertyChanging("ModuleID");
                    _ModuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModuleID");
                    OnModuleIDChanged();
                }
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModuleName
        {
            get
            {
                return _ModuleName;
            }
            set
            {
                OnModuleNameChanging(value);
                ReportPropertyChanging("ModuleName");
                _ModuleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModuleName");
                OnModuleNameChanged();
            }
        }
        private global::System.String _ModuleName;
        partial void OnModuleNameChanging(global::System.String value);
        partial void OnModuleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _status;
        partial void OnstatusChanging(Nullable<global::System.Boolean> value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_EMAILModel", Name="TableStructure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableStructure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TableStructure object.
        /// </summary>
        /// <param name="tS_Id">Initial value of the tS_Id property.</param>
        public static TableStructure CreateTableStructure(global::System.Int32 tS_Id)
        {
            TableStructure tableStructure = new TableStructure();
            tableStructure.tS_Id = tS_Id;
            return tableStructure;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tS_Id
        {
            get
            {
                return _tS_Id;
            }
            set
            {
                if (_tS_Id != value)
                {
                    OntS_IdChanging(value);
                    ReportPropertyChanging("tS_Id");
                    _tS_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tS_Id");
                    OntS_IdChanged();
                }
            }
        }
        private global::System.Int32 _tS_Id;
        partial void OntS_IdChanging(global::System.Int32 value);
        partial void OntS_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tS_Query
        {
            get
            {
                return _tS_Query;
            }
            set
            {
                OntS_QueryChanging(value);
                ReportPropertyChanging("tS_Query");
                _tS_Query = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tS_Query");
                OntS_QueryChanged();
            }
        }
        private global::System.String _tS_Query;
        partial void OntS_QueryChanging(global::System.String value);
        partial void OntS_QueryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tS_FormName
        {
            get
            {
                return _tS_FormName;
            }
            set
            {
                OntS_FormNameChanging(value);
                ReportPropertyChanging("tS_FormName");
                _tS_FormName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tS_FormName");
                OntS_FormNameChanged();
            }
        }
        private global::System.String _tS_FormName;
        partial void OntS_FormNameChanging(global::System.String value);
        partial void OntS_FormNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tS_ControlName
        {
            get
            {
                return _tS_ControlName;
            }
            set
            {
                OntS_ControlNameChanging(value);
                ReportPropertyChanging("tS_ControlName");
                _tS_ControlName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tS_ControlName");
                OntS_ControlNameChanged();
            }
        }
        private global::System.String _tS_ControlName;
        partial void OntS_ControlNameChanging(global::System.String value);
        partial void OntS_ControlNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataBaseName
        {
            get
            {
                return _DataBaseName;
            }
            set
            {
                OnDataBaseNameChanging(value);
                ReportPropertyChanging("DataBaseName");
                _DataBaseName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataBaseName");
                OnDataBaseNameChanged();
            }
        }
        private global::System.String _DataBaseName;
        partial void OnDataBaseNameChanging(global::System.String value);
        partial void OnDataBaseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Select_Clause
        {
            get
            {
                return _Select_Clause;
            }
            set
            {
                OnSelect_ClauseChanging(value);
                ReportPropertyChanging("Select_Clause");
                _Select_Clause = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Select_Clause");
                OnSelect_ClauseChanged();
            }
        }
        private global::System.String _Select_Clause;
        partial void OnSelect_ClauseChanging(global::System.String value);
        partial void OnSelect_ClauseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int64> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int64> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _LastModifiedBy;
        partial void OnLastModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOn
        {
            get
            {
                return _LastModifiedOn;
            }
            set
            {
                OnLastModifiedOnChanging(value);
                ReportPropertyChanging("LastModifiedOn");
                _LastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOn");
                OnLastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOn;
        partial void OnLastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnChanged();

        #endregion

    
    }

    #endregion

    
}
