//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace RBDL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EINS_RBMS_SMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EINS_RBMS_SMSEntities object using the connection string found in the 'EINS_RBMS_SMSEntities' section of the application configuration file.
        /// </summary>
        public EINS_RBMS_SMSEntities() : base("name=EINS_RBMS_SMSEntities", "EINS_RBMS_SMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EINS_RBMS_SMSEntities object.
        /// </summary>
        public EINS_RBMS_SMSEntities(string connectionString) : base(connectionString, "EINS_RBMS_SMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EINS_RBMS_SMSEntities object.
        /// </summary>
        public EINS_RBMS_SMSEntities(EntityConnection connection) : base(connection, "EINS_RBMS_SMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sent> Sents
        {
            get
            {
                if ((_Sents == null))
                {
                    _Sents = base.CreateObjectSet<Sent>("Sents");
                }
                return _Sents;
            }
        }
        private ObjectSet<Sent> _Sents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EventsManager> EventsManagers
        {
            get
            {
                if ((_EventsManagers == null))
                {
                    _EventsManagers = base.CreateObjectSet<EventsManager>("EventsManagers");
                }
                return _EventsManagers;
            }
        }
        private ObjectSet<EventsManager> _EventsManagers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AdditionalContact> AdditionalContacts
        {
            get
            {
                if ((_AdditionalContacts == null))
                {
                    _AdditionalContacts = base.CreateObjectSet<AdditionalContact>("AdditionalContacts");
                }
                return _AdditionalContacts;
            }
        }
        private ObjectSet<AdditionalContact> _AdditionalContacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Group_Details> Group_Details
        {
            get
            {
                if ((_Group_Details == null))
                {
                    _Group_Details = base.CreateObjectSet<Group_Details>("Group_Details");
                }
                return _Group_Details;
            }
        }
        private ObjectSet<Group_Details> _Group_Details;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSents(Sent sent)
        {
            base.AddObject("Sents", sent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EventsManagers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventsManagers(EventsManager eventsManager)
        {
            base.AddObject("EventsManagers", eventsManager);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AdditionalContacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdditionalContacts(AdditionalContact additionalContact)
        {
            base.AddObject("AdditionalContacts", additionalContact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Group_Details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroup_Details(Group_Details group_Details)
        {
            base.AddObject("Group_Details", group_Details);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_SMSModel", Name="AdditionalContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AdditionalContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AdditionalContact object.
        /// </summary>
        /// <param name="additionalContId">Initial value of the AdditionalContId property.</param>
        public static AdditionalContact CreateAdditionalContact(global::System.Int32 additionalContId)
        {
            AdditionalContact additionalContact = new AdditionalContact();
            additionalContact.AdditionalContId = additionalContId;
            return additionalContact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdditionalContId
        {
            get
            {
                return _AdditionalContId;
            }
            set
            {
                if (_AdditionalContId != value)
                {
                    OnAdditionalContIdChanging(value);
                    ReportPropertyChanging("AdditionalContId");
                    _AdditionalContId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdditionalContId");
                    OnAdditionalContIdChanged();
                }
            }
        }
        private global::System.Int32 _AdditionalContId;
        partial void OnAdditionalContIdChanging(global::System.Int32 value);
        partial void OnAdditionalContIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNo
        {
            get
            {
                return _ContactNo;
            }
            set
            {
                OnContactNoChanging(value);
                ReportPropertyChanging("ContactNo");
                _ContactNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNo");
                OnContactNoChanged();
            }
        }
        private global::System.String _ContactNo;
        partial void OnContactNoChanging(global::System.String value);
        partial void OnContactNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int64> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int64> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _LastModifiedBy;
        partial void OnLastModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOn
        {
            get
            {
                return _LastModifiedOn;
            }
            set
            {
                OnLastModifiedOnChanging(value);
                ReportPropertyChanging("LastModifiedOn");
                _LastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOn");
                OnLastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOn;
        partial void OnLastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_SMSModel", Name="EventsManager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventsManager : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventsManager object.
        /// </summary>
        /// <param name="event_Id">Initial value of the Event_Id property.</param>
        public static EventsManager CreateEventsManager(global::System.Int32 event_Id)
        {
            EventsManager eventsManager = new EventsManager();
            eventsManager.Event_Id = event_Id;
            return eventsManager;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Event_Id
        {
            get
            {
                return _Event_Id;
            }
            set
            {
                if (_Event_Id != value)
                {
                    OnEvent_IdChanging(value);
                    ReportPropertyChanging("Event_Id");
                    _Event_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Event_Id");
                    OnEvent_IdChanged();
                }
            }
        }
        private global::System.Int32 _Event_Id;
        partial void OnEvent_IdChanging(global::System.Int32 value);
        partial void OnEvent_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventName
        {
            get
            {
                return _EventName;
            }
            set
            {
                OnEventNameChanging(value);
                ReportPropertyChanging("EventName");
                _EventName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventName");
                OnEventNameChanged();
            }
        }
        private global::System.String _EventName;
        partial void OnEventNameChanging(global::System.String value);
        partial void OnEventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_ModuleId
        {
            get
            {
                return _eM_ModuleId;
            }
            set
            {
                OneM_ModuleIdChanging(value);
                ReportPropertyChanging("eM_ModuleId");
                _eM_ModuleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_ModuleId");
                OneM_ModuleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_ModuleId;
        partial void OneM_ModuleIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_ModuleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_FormId
        {
            get
            {
                return _eM_FormId;
            }
            set
            {
                OneM_FormIdChanging(value);
                ReportPropertyChanging("eM_FormId");
                _eM_FormId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_FormId");
                OneM_FormIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_FormId;
        partial void OneM_FormIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_FormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_Event_Id
        {
            get
            {
                return _eM_Event_Id;
            }
            set
            {
                OneM_Event_IdChanging(value);
                ReportPropertyChanging("eM_Event_Id");
                _eM_Event_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_Event_Id");
                OneM_Event_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_Event_Id;
        partial void OneM_Event_IdChanging(Nullable<global::System.Int32> value);
        partial void OneM_Event_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_CompanyId
        {
            get
            {
                return _eM_CompanyId;
            }
            set
            {
                OneM_CompanyIdChanging(value);
                ReportPropertyChanging("eM_CompanyId");
                _eM_CompanyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_CompanyId");
                OneM_CompanyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_CompanyId;
        partial void OneM_CompanyIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_CompanyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eM_LocationId
        {
            get
            {
                return _eM_LocationId;
            }
            set
            {
                OneM_LocationIdChanging(value);
                ReportPropertyChanging("eM_LocationId");
                _eM_LocationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eM_LocationId");
                OneM_LocationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eM_LocationId;
        partial void OneM_LocationIdChanging(Nullable<global::System.Int32> value);
        partial void OneM_LocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommonSMSBody
        {
            get
            {
                return _CommonSMSBody;
            }
            set
            {
                OnCommonSMSBodyChanging(value);
                ReportPropertyChanging("CommonSMSBody");
                _CommonSMSBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommonSMSBody");
                OnCommonSMSBodyChanged();
            }
        }
        private global::System.String _CommonSMSBody;
        partial void OnCommonSMSBodyChanging(global::System.String value);
        partial void OnCommonSMSBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HostSMSBody
        {
            get
            {
                return _HostSMSBody;
            }
            set
            {
                OnHostSMSBodyChanging(value);
                ReportPropertyChanging("HostSMSBody");
                _HostSMSBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HostSMSBody");
                OnHostSMSBodyChanged();
            }
        }
        private global::System.String _HostSMSBody;
        partial void OnHostSMSBodyChanging(global::System.String value);
        partial void OnHostSMSBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VisitorSMSBody
        {
            get
            {
                return _VisitorSMSBody;
            }
            set
            {
                OnVisitorSMSBodyChanging(value);
                ReportPropertyChanging("VisitorSMSBody");
                _VisitorSMSBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VisitorSMSBody");
                OnVisitorSMSBodyChanged();
            }
        }
        private global::System.String _VisitorSMSBody;
        partial void OnVisitorSMSBodyChanging(global::System.String value);
        partial void OnVisitorSMSBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeContact
        {
            get
            {
                return _EmployeeContact;
            }
            set
            {
                OnEmployeeContactChanging(value);
                ReportPropertyChanging("EmployeeContact");
                _EmployeeContact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeContact");
                OnEmployeeContactChanged();
            }
        }
        private global::System.String _EmployeeContact;
        partial void OnEmployeeContactChanging(global::System.String value);
        partial void OnEmployeeContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdditionalContact
        {
            get
            {
                return _AdditionalContact;
            }
            set
            {
                OnAdditionalContactChanging(value);
                ReportPropertyChanging("AdditionalContact");
                _AdditionalContact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdditionalContact");
                OnAdditionalContactChanged();
            }
        }
        private global::System.String _AdditionalContact;
        partial void OnAdditionalContactChanging(global::System.String value);
        partial void OnAdditionalContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupIds
        {
            get
            {
                return _GroupIds;
            }
            set
            {
                OnGroupIdsChanging(value);
                ReportPropertyChanging("GroupIds");
                _GroupIds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupIds");
                OnGroupIdsChanged();
            }
        }
        private global::System.String _GroupIds;
        partial void OnGroupIdsChanging(global::System.String value);
        partial void OnGroupIdsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CheckForHost
        {
            get
            {
                return _CheckForHost;
            }
            set
            {
                OnCheckForHostChanging(value);
                ReportPropertyChanging("CheckForHost");
                _CheckForHost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckForHost");
                OnCheckForHostChanged();
            }
        }
        private Nullable<global::System.Boolean> _CheckForHost;
        partial void OnCheckForHostChanging(Nullable<global::System.Boolean> value);
        partial void OnCheckForHostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CheckForVisitor
        {
            get
            {
                return _CheckForVisitor;
            }
            set
            {
                OnCheckForVisitorChanging(value);
                ReportPropertyChanging("CheckForVisitor");
                _CheckForVisitor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheckForVisitor");
                OnCheckForVisitorChanged();
            }
        }
        private Nullable<global::System.Boolean> _CheckForVisitor;
        partial void OnCheckForVisitorChanging(Nullable<global::System.Boolean> value);
        partial void OnCheckForVisitorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int32> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int32> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _LastModifiedBy;
        partial void OnLastModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOn
        {
            get
            {
                return _LastModifiedOn;
            }
            set
            {
                OnLastModifiedOnChanging(value);
                ReportPropertyChanging("LastModifiedOn");
                _LastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOn");
                OnLastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOn;
        partial void OnLastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_SMSModel", Name="Group_Details")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Group_Details : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Group_Details object.
        /// </summary>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        public static Group_Details CreateGroup_Details(global::System.Int32 groupID)
        {
            Group_Details group_Details = new Group_Details();
            group_Details.GroupID = groupID;
            return group_Details;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupDescription
        {
            get
            {
                return _GroupDescription;
            }
            set
            {
                OnGroupDescriptionChanging(value);
                ReportPropertyChanging("GroupDescription");
                _GroupDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupDescription");
                OnGroupDescriptionChanged();
            }
        }
        private global::System.String _GroupDescription;
        partial void OnGroupDescriptionChanging(global::System.String value);
        partial void OnGroupDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Grp_Contacts_Emp
        {
            get
            {
                return _Grp_Contacts_Emp;
            }
            set
            {
                OnGrp_Contacts_EmpChanging(value);
                ReportPropertyChanging("Grp_Contacts_Emp");
                _Grp_Contacts_Emp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Grp_Contacts_Emp");
                OnGrp_Contacts_EmpChanged();
            }
        }
        private global::System.String _Grp_Contacts_Emp;
        partial void OnGrp_Contacts_EmpChanging(global::System.String value);
        partial void OnGrp_Contacts_EmpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Grp_Contacts_Add
        {
            get
            {
                return _Grp_Contacts_Add;
            }
            set
            {
                OnGrp_Contacts_AddChanging(value);
                ReportPropertyChanging("Grp_Contacts_Add");
                _Grp_Contacts_Add = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Grp_Contacts_Add");
                OnGrp_Contacts_AddChanged();
            }
        }
        private global::System.String _Grp_Contacts_Add;
        partial void OnGrp_Contacts_AddChanging(global::System.String value);
        partial void OnGrp_Contacts_AddChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanyId
        {
            get
            {
                return _CompanyId;
            }
            set
            {
                OnCompanyIdChanging(value);
                ReportPropertyChanging("CompanyId");
                _CompanyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyId");
                OnCompanyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanyId;
        partial void OnCompanyIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompanyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                OnLocationIdChanging(value);
                ReportPropertyChanging("LocationId");
                _LocationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationId");
                OnLocationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationId;
        partial void OnLocationIdChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _status;
        partial void OnstatusChanging(Nullable<global::System.Boolean> value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int64> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int64> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _LastModifiedBy;
        partial void OnLastModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedOn
        {
            get
            {
                return _LastModifiedOn;
            }
            set
            {
                OnLastModifiedOnChanging(value);
                ReportPropertyChanging("LastModifiedOn");
                _LastModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedOn");
                OnLastModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedOn;
        partial void OnLastModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EINS_RBMS_SMSModel", Name="Sent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sent object.
        /// </summary>
        /// <param name="sentId">Initial value of the SentId property.</param>
        public static Sent CreateSent(global::System.Int64 sentId)
        {
            Sent sent = new Sent();
            sent.SentId = sentId;
            return sent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SentId
        {
            get
            {
                return _SentId;
            }
            set
            {
                if (_SentId != value)
                {
                    OnSentIdChanging(value);
                    ReportPropertyChanging("SentId");
                    _SentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SentId");
                    OnSentIdChanged();
                }
            }
        }
        private global::System.Int64 _SentId;
        partial void OnSentIdChanging(global::System.Int64 value);
        partial void OnSentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNo
        {
            get
            {
                return _ContactNo;
            }
            set
            {
                OnContactNoChanging(value);
                ReportPropertyChanging("ContactNo");
                _ContactNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNo");
                OnContactNoChanged();
            }
        }
        private global::System.String _ContactNo;
        partial void OnContactNoChanging(global::System.String value);
        partial void OnContactNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message_Status
        {
            get
            {
                return _Message_Status;
            }
            set
            {
                OnMessage_StatusChanging(value);
                ReportPropertyChanging("Message_Status");
                _Message_Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message_Status");
                OnMessage_StatusChanged();
            }
        }
        private global::System.String _Message_Status;
        partial void OnMessage_StatusChanging(global::System.String value);
        partial void OnMessage_StatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormName
        {
            get
            {
                return _FormName;
            }
            set
            {
                OnFormNameChanging(value);
                ReportPropertyChanging("FormName");
                _FormName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormName");
                OnFormNameChanged();
            }
        }
        private global::System.String _FormName;
        partial void OnFormNameChanging(global::System.String value);
        partial void OnFormNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ScheduleId
        {
            get
            {
                return _ScheduleId;
            }
            set
            {
                OnScheduleIdChanging(value);
                ReportPropertyChanging("ScheduleId");
                _ScheduleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleId");
                OnScheduleIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ScheduleId;
        partial void OnScheduleIdChanging(Nullable<global::System.Int64> value);
        partial void OnScheduleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AppointmentId
        {
            get
            {
                return _AppointmentId;
            }
            set
            {
                OnAppointmentIdChanging(value);
                ReportPropertyChanging("AppointmentId");
                _AppointmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppointmentId");
                OnAppointmentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _AppointmentId;
        partial void OnAppointmentIdChanging(Nullable<global::System.Int64> value);
        partial void OnAppointmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private Nullable<global::System.Int64> _AddedBy;
        partial void OnAddedByChanging(Nullable<global::System.Int64> value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AddedOn
        {
            get
            {
                return _AddedOn;
            }
            set
            {
                OnAddedOnChanging(value);
                ReportPropertyChanging("AddedOn");
                _AddedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedOn");
                OnAddedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _AddedOn;
        partial void OnAddedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnAddedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Sms_Status
        {
            get
            {
                return _Sms_Status;
            }
            set
            {
                OnSms_StatusChanging(value);
                ReportPropertyChanging("Sms_Status");
                _Sms_Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sms_Status");
                OnSms_StatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Sms_Status;
        partial void OnSms_StatusChanging(Nullable<global::System.Boolean> value);
        partial void OnSms_StatusChanged();

        #endregion

    
    }

    #endregion

    
}
